def projectname = "master demo"
def isChange = false
def cron_string = env.ENVIRONMENT == "QA" ? '* * * * *' : ''

pipeline {
    agent any
    triggers {
        cron(cron_string)
    }     
    stages {
        stage('Check Any change') {
            steps {
                script {
                    println "${cron_string}"
                    if (GIT_PREVIOUS_SUCCESSFUL_COMMIT != GIT_COMMIT) {
                        isChange = true
                    }
                }
            }
        }
        stage('Build') {
            steps {
               script {
                    if(isChange) {
                        echo "change"
                    } else {
                        echo "not change"
                    }
               }
            }
        }
    }
}
